version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: ms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    container_name: ms-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always

  wiremock-wwe-server:
    image: wiremock/wiremock:2.32.0
    ports:
      - 3001:8080
    volumes:
      - ./wiremock:/home/wiremock/

volumes:
  redis-data:
  mongo-data:
